name: C# CI

on:
  push:
    branches: [ "main" ] # Or your main branch name
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore CybersecurityChatbot.sln # Replace with your solution file name

    - name: Build project
      run: msbuild CybersecurityChatbot.sln /p:Configuration=Release # Replace with your solution file name

    - name: Run tests (if you have them)
      run: dotnet test CybersecurityChatbot.Tests/CybersecurityChatbot.Tests.csproj # Replace with your test project path

    - name: Code Formatting Check (using dotnet format)
      run: dotnet format --verify-no-changes CybersecurityChatbot.sln # Replace with your solution file name

